### ISSUE TITLE
D&D 5e Skills missing in the HUD

### ISSUE THREAD

**Issue by trdischat** [espositos/fvtt-tokenactionhud#289] opened 2021-06-23 07:58 UTC
Running version 1.1.4 of Token Action HUD in FVTT 0.8.7 with dnd5e 1.3.5, and no other modules enabled. With the latest version, Skills no longer appear as a tab in the HUD.

**Comment by makhmud** [comment] 2021-06-23 10:52
So do "Spells" category
I believe mistake is here:
https://github.com/espositos/fvtt-tokenactionhud/blob/f0eb5f787f0c029e6b95d24caa4de898dc587369/scripts/actions/dnd5e/dnd5e-actions.js#L198
https://github.com/espositos/fvtt-tokenactionhud/blob/f0eb5f787f0c029e6b95d24caa4de898dc587369/scripts/actions/dnd5e/dnd5e-actions.js#L421
I think line
`if (actor.data.type !== 'vehicle') return;`
should be replaced with
`if (actor.data.type === 'vehicle') return;`

**Comment by ranky** [comment] 2021-06-23 11:51
https://github.com/espositos/fvtt-tokenactionhud/blob/f0eb5f787f0c029e6b95d24caa4de898dc587369/scripts/actions/dnd5e/dnd5e-actions.js#L436

This line should also be changed to 
`let encodedValue = [macroType, token.id, e[0]].join(this.delimiter);`

**Comment by vanderleitelesjr** [comment] 2021-06-23 15:02
> 
> 
> So do "Spells" category
> I believe mistake is here:
> 
> https://github.com/espositos/fvtt-tokenactionhud/blob/f0eb5f787f0c029e6b95d24caa4de898dc587369/scripts/actions/dnd5e/dnd5e-actions.js#L198
> 
> https://github.com/espositos/fvtt-tokenactionhud/blob/f0eb5f787f0c029e6b95d24caa4de898dc587369/scripts/actions/dnd5e/dnd5e-actions.js#L421
> 
> I think line
> `if (actor.data.type !== 'vehicle') return;`
> should be replaced with
> `if (actor.data.type === 'vehicle') return;`



> 
> 
> https://github.com/espositos/fvtt-tokenactionhud/blob/f0eb5f787f0c029e6b95d24caa4de898dc587369/scripts/actions/dnd5e/dnd5e-actions.js#L436
> 
> This line should also be changed to
> `let encodedValue = [macroType, token.id, e[0]].join(this.delimiter);`

Both are correct

**Comment by Gacky2k** [comment] 2021-06-23 15:27
Yah..sucked that this is broken. My players really enjoy it, and had to roll from character sheet last night, or drag to quick bar at the bottom.  Hopefully he fixes it soon  :)   Love this module!

**Comment by Tam1974** [comment] 2021-06-23 15:56
This is my Players favourite tool - hopefully it will be mended soon.....????

**Comment by solistahoe** [comment] 2021-06-23 15:59
> > So do "Spells" category
> > I believe mistake is here:
> > https://github.com/espositos/fvtt-tokenactionhud/blob/f0eb5f787f0c029e6b95d24caa4de898dc587369/scripts/actions/dnd5e/dnd5e-actions.js#L198
> > 
> > https://github.com/espositos/fvtt-tokenactionhud/blob/f0eb5f787f0c029e6b95d24caa4de898dc587369/scripts/actions/dnd5e/dnd5e-actions.js#L421
> > 
> > I think line
> > `if (actor.data.type !== 'vehicle') return;`
> > should be replaced with
> > `if (actor.data.type === 'vehicle') return;`
> 
> > https://github.com/espositos/fvtt-tokenactionhud/blob/f0eb5f787f0c029e6b95d24caa4de898dc587369/scripts/actions/dnd5e/dnd5e-actions.js#L436
> > 
> > This line should also be changed to
> > `let encodedValue = [macroType, token.id, e[0]].join(this.delimiter);`
> 
> Both are correct

IT TOTALLY WORKED! THANK YOU!

**Comment by Matt-BW** [comment] 2021-06-23 22:19
Thanks for the info, this has partially worked for me which is great. Some characters can only see 1 spell per level oddly.

**Comment by benbarbour** [comment] 2021-06-24 02:29
Sorry guys, this is my fault. @espositos  merged my PR for #91 and I didn't test it enough in "normal mode". I'll try to find time tonight to fix it.

**Comment by benbarbour** [comment] 2021-06-24 19:55
Until my PR is merged to fix this (or until @espositos releases his own fix) you could install Character Actions List and then click the "Group by Action Type" setting in this module's settings. You might also want to edit the Character Actions List settings to prevent sheet injection.

Spells and Skills will show up in this mode, even with the current version. But instead of all spells showing up under "Spells", they'll show up under "Actions", "Bonus Actions", or "Reactions" as appropriate, asking with other Actions, Bonus Actions, and Reactions that you might have. They'll still be grouped by level, need to be prepared and have spell slots to show up, etc.

I don't know if you'll like the grouping, but at least you'll be able to find the missing items in the HUD.

**Comment by dsakura** [comment] 2021-06-25 15:59
Hello! the Skill category is still missing after the fix, only spell returned. Thank you

**Comment by benbarbour** [comment] 2021-06-25 17:27
You changed the `if (actor.data.type !== 'vehicle') return;` line in both places? I just tested again and I can't reproduce that - skills are showing up for me.

**Closed** 2021-06-26 21:08 UTC
