### ISSUE TITLE
Token action hud not appearing in latest update

### ISSUE THREAD

**Issue by Avitale34** [espositos/fvtt-tokenactionhud#257] opened 2021-06-08 13:15 UTC
Just updated this morning and can no longer get the HUD to show up.

**Comment by ExileofBrokenSky** [comment] 2021-06-08 13:22
Same, but fiddling with the console looks like there is an error with the Item Macro mod, when I disabled that one, HUD was back.

**Comment by Arx724** [comment] 2021-06-08 14:26
Same, for now I just went back to [1.0.21](https://github.com/espositos/fvtt-tokenactionhud/releases/tag/1.0.21).

**Comment by Cosmic-Lattee** [comment] 2021-06-08 14:53
I don't have the Item Macro mod and I am having the issue. This is the error that was pulled up when clicking on a token in my game:

![image](https://user-images.githubusercontent.com/24766235/121207942-4c16f580-c83f-11eb-8b7e-e86d23a42dce.png)

I am running a PF2E game.

**Comment by Cosmic-Lattee** [comment] 2021-06-08 15:09
Alright so through some trial and error I determined that the error is coming items. Weapons, armor, anything that is equipped and treasure is causing the issue.

**Comment by mklummis** [comment] 2021-06-08 16:06
I had the exact same result. Equip anything, lose the HUD. Take everything off, HUD comes right back. Livable for spellcasters, but man I hope this isn't a hard bug to squash. (Also playing Pathfinder 2e)

**Comment by laurieathey** [comment] 2021-06-08 16:37
PF2E, same issue as above as far as I can tell.
The error
`
pf2e-actions.js:165 Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at pf2e-actions.js:165
    at Map.filter (collection.mjs:66)
    at ActionHandlerPf2e._getItemsList (pf2e-actions.js:165)
    at PcActionHandlerPf2e._forCharacter (pf2e-actions-pc.js:45)
    at PcActionHandlerPf2e.buildActionList (pf2e-actions-pc.js:15)
    at ActionHandlerPf2e.doBuildActionList (pf2e-actions.js:40)
    at ActionHandlerPf2e.buildActionList (actionHandler.js:32)
    at TokenActionHUD.updateHud (tokenactionhud.js:386)
`
There's a really spammy warning above it as well, which as far as I can tell happens at the same time.

`foundry.js:9717 The Document#_id property is deprecated in favor of Document#id or Document#data#_id. Support will be removed in 0.9.0`

Also confirmed the above reports of equiping items causing the issue. 
Once I unequpiped all items from my test character the bar came back, and no error in the console. Still got the wall of warnings though.

Good luck fixing, this mod is one of my favourites :)

**Comment by apoapostolov** [comment] 2021-06-08 18:18
@laurieathey the issue is known related to equipped items. Try to unequip all items from a character and see if the HUD shows, it should.

**Comment by AdamantiteAdventurer** [comment] 2021-06-08 18:42
The HUD does reappear when you unequip everything, but as a Fighter and Monk it's isn't feasible.

**Comment by espositos** [comment] 2021-06-08 19:00
Should be fixed, as always let me know if it's not

**Closed by espositos** 2021-06-08 19:00 UTC
